openapi: "3.0.3"

info:
    version: 0.1.0
    title: ordersApp
    description: App that enables you to work with your orders

tags:
    - name: Orders
    - name: Login

components:
    schemas:
        $ref: "./schemas/index.yaml"

    responses:
        $ref: "./responses/index.yaml"

    requestBodies:
        $ref: "./requestBodies/index.yaml"

paths:
    /orders/{userId}:
        $ref: "./paths/orders.yaml"

    /order/{orderId}:
        $ref: "./paths/order.yaml"

    /login:
        $ref: "./paths/login.yaml"

    /signUp:
        $ref: "./paths/signUp.yaml"

    /orders/week/{date-userId}:
        $ref: "./paths/orders_date_week.yaml"

    /orders/day/{date-userId}:
        $ref: "./paths/orders_date_day.yaml"


